
# resume information
resume-index = 509684
seed = 2121689879806327540
rate = 1000      
shard = 1/1
nocapture = servername

output-filename = /opt/vanta/reports/192.168.18.0/24_20260527_210223/masscan.txt
output-format = grepable

adapter-ip = 172.18.2.107
# TARGET SELECTION (IP, PORTS, EXCLUDES)
ports = 1-65535
range = 192.168.18.0/24

